x-redis-common: &redis-common
  build:
    context: .
    dockerfile: ./configs/ha/replica/Dockerfile
  restart: always
  networks:
    redisnet:
      ipv4_address: 0.0.0.0

x-sentinel-common: &sentinel-common
  build:
    context: .
    dockerfile: ./configs/ha/sentinel/Dockerfile
  restart: always
  networks:
    redisnet:
      ipv4_address: 0.0.0.0
  depends_on:
    - redis-master

services:
  redis-master:
    <<: *redis-common
    container_name: redis-master
    image: thuongtruong1009/reluster-replica
    volumes:
      - ./configs/ha/replica/master.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      redisnet:
        ipv4_address: 172.28.0.10
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "masterpass", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  slave_1:
    image: thuongtruong1009/reluster-replica
    container_name: slave_1
    volumes:
      - ./configs/ha/replica/slave.conf:/etc/redis/redis.conf
    ports:
      - "6380:6379"
    networks:
      redisnet:
        ipv4_address: 172.28.0.11
    depends_on:
      - redis-master

  slave_2:
    image: thuongtruong1009/reluster-replica
    container_name: slave_2
    volumes:
      - ./configs/ha/replica/slave.conf:/etc/redis/redis.conf
    ports:
      - "6381:6379"
    networks:
      redisnet:
        ipv4_address: 172.28.0.12
    depends_on:
      - redis-master

  slave_3:
    image: thuongtruong1009/reluster-replica
    container_name: slave_3
    volumes:
      - ./configs/ha/replica/slave.conf:/etc/redis/redis.conf
    ports:
      - "6382:6379"
    networks:
      redisnet:
        ipv4_address: 172.28.0.13
    depends_on:
      - redis-master

  sentinel_1:
    <<: *sentinel-common
    container_name: sentinel_1
    image: thuongtruong1009/reluster-sentinel
    ports:
      - "26379:26379"
    networks:
      redisnet:
        ipv4_address: 172.28.0.20

  sentinel_2:
    <<: *sentinel-common
    container_name: sentinel_2
    image: thuongtruong1009/reluster-sentinel
    ports:
      - "26380:26379"
    networks:
      redisnet:
        ipv4_address: 172.28.0.21

  sentinel_3:
    <<: *sentinel-common
    container_name: sentinel_3
    image: thuongtruong1009/reluster-sentinel
    ports:
      - "26381:26379"
    networks:
      redisnet:
        ipv4_address: 172.28.0.22

networks:
  redisnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
