services:
  commander:
    image: rediscommander/redis-commander:latest
    container_name: commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./configs/commander/${CONFIG_PATH}:/redis-commander/config/local-production.json:ro
    networks:
      - redisnet

networks:
  redisnet:
    external: true
