services:
  sentinel_1:
    volumes:
      - ./sentinel.ci.conf:/etc/redis/sentinel.conf
  sentinel_2:
    volumes:
      - ./sentinel.ci.conf:/etc/redis/sentinel.conf
  sentinel_3:
    volumes:
      - ./sentinel.ci.conf:/etc/redis/sentinel.conf
