services:
  commander:
    image: rediscommander/redis-commander:latest
    container_name: commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./tools/commander/${CONFIG_PATH}:/redis-commander/config/local-production.json:ro
    networks:
      - redisnet

  exporter:
    image: oliver006/redis_exporter:v1.50.0
    container_name: exporter
    networks:
      - redisnet
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_ADDR: "node-1:6379,node-2:6379,node-3:6379,node-4:6379,node-5:6379,node-6:6379"
      REDIS_CLUSTER_MODE: "true"
    ports:
      - "9121:9121"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9121/metrics"]
      interval: 15s
      retries: 3

  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: prometheus
    networks:
      - redisnet
    volumes:
      - ./tools/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - exporter

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    networks:
      - redisnet
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    volumes:
      - ./tools/grafana/data:/var/lib/grafana
    depends_on:
      - prometheus

networks:
  redisnet:
    external: true
