services:
  node-1:
    image: redis:7.2
    container_name: node-1
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./master/cluster.conf:/etc/redis/redis.conf
      - node-1-data:/data
    ports:
      - "7001:6379"
    networks:
      redisnet:
        ipv4_address: 172.28.0.11

  node-2:
    image: redis:7.2
    container_name: node-2
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./master/cluster.conf:/etc/redis/redis.conf
      - node-2-data:/data
    ports:
      - "7002:6379"
    networks:
      redisnet:
        ipv4_address: 172.28.0.12

  node-3:
    image: redis:7.2
    container_name: node-3
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./master/cluster.conf:/etc/redis/redis.conf
      - node-3-data:/data
    ports:
      - "7003:6379"
    networks:
      redisnet:
        ipv4_address: 172.28.0.13

  node-4:
    image: redis:7.2
    container_name: node-4
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./master/cluster.conf:/etc/redis/redis.conf
      - node-4-data:/data
    ports:
      - "7004:6379"
    networks:
      redisnet:
        ipv4_address: 172.28.0.14

  node-5:
    image: redis:7.2
    container_name: node-5
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./master/cluster.conf:/etc/redis/redis.conf
      - node-5-data:/data
    ports:
      - "7005:6379"
    networks:
      redisnet:
        ipv4_address: 172.28.0.15

  node-6:
    image: redis:7.2
    container_name: node-6
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./master/cluster.conf:/etc/redis/redis.conf
      - node-6-data:/data
    ports:
      - "7006:6379"
    networks:
      redisnet:
        ipv4_address: 172.28.0.16

networks:
  redisnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  node-1-data:
  node-2-data:
  node-3-data:
  node-4-data:
  node-5-data:
  node-6-data:
