x-node-base: &node-base
  image: thuongtruong1009/reluster:latest
  build:
    context: .
    dockerfile: ./configs/cluster/Dockerfile
  networks:
    - redisnet
  environment:
    - ANNOUNCE_IP=
  healthcheck:
    test: ["CMD", "redis-cli", "ping"]
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 10s

services:
  node-1:
    <<: *node-base
    container_name: node-1
    environment:
      - ANNOUNCE_IP=node-1
    ports:
      - "7001:6379"
    volumes:
      - node-1-data:/data

  node-2:
    <<: *node-base
    container_name: node-2
    environment:
      - ANNOUNCE_IP=node-2
    ports:
      - "7002:6379"
    volumes:
      - node-2-data:/data

  node-3:
    <<: *node-base
    container_name: node-3
    environment:
      - ANNOUNCE_IP=node-3
    ports:
      - "7003:6379"
    volumes:
      - node-3-data:/data

  node-4:
    <<: *node-base
    container_name: node-4
    environment:
      - ANNOUNCE_IP=node-4
    ports:
      - "7004:6379"
    volumes:
      - node-4-data:/data

  node-5:
    <<: *node-base
    container_name: node-5
    environment:
      - ANNOUNCE_IP=node-5
    ports:
      - "7005:6379"
    volumes:
      - node-5-data:/data

  node-6:
    <<: *node-base
    container_name: node-6
    environment:
      - ANNOUNCE_IP=node-6
    ports:
      - "7006:6379"
    volumes:
      - node-6-data:/data

  node-7:
    <<: *node-base
    container_name: node-7
    environment:
      - ANNOUNCE_IP=node-7
    ports:
      - "7007:6379"
    volumes:
      - node-7-data:/data

networks:
  redisnet:
    name: redisnet
    driver: bridge

volumes:
  node-1-data:
  node-2-data:
  node-3-data:
  node-4-data:
  node-5-data:
  node-6-data:
  node-7-data:
