version: "3.9"

services:
  redis-master:
    image: redis:7.2
    container_name: redis-master
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./master/ha.conf:/etc/redis/redis.conf
    networks:
      redisnet:
        ipv4_address: 172.30.0.10

  slave_1:
    image: redis:7.2
    container_name: slave_1
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./slave.ci.conf:/etc/redis/redis.conf
    depends_on:
      - redis-master
    networks:
      redisnet:
        ipv4_address: 172.30.0.11

  slave_2:
    image: redis:7.2
    container_name: slave_2
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./slave.ci.conf:/etc/redis/redis.conf
    depends_on:
      - redis-master
    networks:
      redisnet:
        ipv4_address: 172.30.0.12

  slave_3:
    image: redis:7.2
    container_name: slave_3
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./slave.ci.conf:/etc/redis/redis.conf
    depends_on:
      - redis-master
    networks:
      redisnet:
        ipv4_address: 172.30.0.13

  sentinel_1:
    image: redis:7.2
    container_name: sentinel_1
    command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
    volumes:
      - ./sentinel.ci.conf:/etc/redis/sentinel.conf
    networks:
      redisnet:
        ipv4_address: 172.30.0.20
    depends_on:
      - redis-master

  sentinel_2:
    image: redis:7.2
    container_name: sentinel_2
    command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
    volumes:
      - ./sentinel.ci.conf:/etc/redis/sentinel.conf
    networks:
      redisnet:
        ipv4_address: 172.30.0.21
    depends_on:
      - redis-master

  sentinel_3:
    image: redis:7.2
    container_name: sentinel_3
    command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
    volumes:
      - ./sentinel.ci.conf:/etc/redis/sentinel.conf
    networks:
      redisnet:
        ipv4_address: 172.30.0.22
    depends_on:
      - redis-master

networks:
  redisnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
