networks:
  redisnet:
    name: redisnet
    driver: bridge

x-redis-base: &redis-base
  image: thuongtruong1009/reluster:latest
  build:
    context: .
    dockerfile: ./configs/cluster/Dockerfile
  environment:
    REDIS_PASSWORD: ${REDIS_PASSWORD}
  networks:
    - redisnet
  healthcheck:
    test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 10s

services:
  node-1:
    <<: *redis-base
    container_name: node-1
    ports:
      - "6379:6379"
      - "16379:16379"

  node-2:
    <<: *redis-base
    container_name: node-2
    ports:
      - "6380:6379"
      - "16380:16379"

  node-3:
    <<: *redis-base
    container_name: node-3
    ports:
      - "6381:6379"
      - "16381:16379"

  node-4:
    <<: *redis-base
    container_name: node-4
    ports:
      - "6382:6379"
      - "16382:16379"

  node-5:
    <<: *redis-base
    container_name: node-5
    ports:
      - "6383:6379"
      - "16383:16379"

  node-6:
    <<: *redis-base
    container_name: node-6
    ports:
      - "6384:6379"
      - "16384:16379"

  benchmark:
    image: thuongtruong1009/reluster-bench:latest
    container_name: benchmark
    build:
      context: .
      dockerfile: ./configs/cluster/Dockerfile.bench
    environment:
      - CLUSTER_PASS=${REDIS_PASSWORD}
      - REDIS_HOST=127.0.0.1
    networks:
      - redisnet
    volumes:
      - ./benchmark-results:/benchmark-results
    depends_on:
      - node-1
      - node-2
      - node-3
