version: "3.9"

networks:
  redisnet:
    name: redisnet
    driver: bridge

x-redis-base: &redis-base
  image: thuongtruong1009/reluster:latest
  build:
    context: .
    dockerfile: ./configs/cluster/Dockerfile
  networks:
    - redisnet
  environment:
    REDIS_PASSWORD: ${REDIS_PASSWORD} # password chung
  healthcheck:
    test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 10s

services:
  node-1:
    <<: *redis-base
    container_name: node-1
    hostname: node-1
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD} # merge password từ base
      REDIS_HOST: node-1

  node-2:
    <<: *redis-base
    container_name: node-2
    hostname: node-2
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: node-2

  node-3:
    <<: *redis-base
    container_name: node-3
    hostname: node-3
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: node-3

  node-4:
    <<: *redis-base
    container_name: node-4
    hostname: node-4
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: node-4

  node-5:
    <<: *redis-base
    container_name: node-5
    hostname: node-5
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: node-5

  node-6:
    <<: *redis-base
    container_name: node-6
    hostname: node-6
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: node-6

  node-7: # failover / future replica
    <<: *redis-base
    container_name: node-7
    hostname: node-7
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: node-7

  benchmark:
    <<: *redis-base
    container_name: benchmark
    entrypoint: ["./tests/clt-bench.sh"]
    networks:
      - redisnet
    environment:
      # CLUSTER_PASS: ${REDIS_PASSWORD}
      REDIS_HOST: node-1
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./results:/results
    depends_on:
      - node-1
      - node-2
      - node-3
      - node-4
      - node-5
      - node-6
