name: 🐛 Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: [bug]

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Provide a detailed description of the bug
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a new project
        2. Install the package
        3. Configure it
        4. Run the build
        5. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Suggested solution
      description: Suggest a fix/reason for the bug
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Additional context about the problem.
    validations:
      required: false
